name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/LESS-DB/LESS-DB
      - name: Pull the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
      - name: Check formatting
        run: |
          make format
      - name: Build library
        run: |
          make lib
      - name: Lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test